import numpy as np

DIM = 4
NBLADES = 2**DIM

# e1² = e2² = ep² = +1, en² = -1
METRIC = np.array([1.0, 1.0, 1.0, -1.0])



def blade_grade(mask):
    return mask.bit_count()

def basis(mask):
    x = np.zeros(16)
    x[mask] = 1.0
    return x


"""
ORDER OF THE BASIS
0: 1     |  4: ep      | 8:  en       | 12: ep,en
1: e1    |  5: e1,ep   | 9:  e1,en    | 13: e1,ep,en
2: e2    |  6: e2,ep   | 10: e2,en    | 14: e2,ep,en
3: e1,e2 |  7: e1,e2,ep| 11: e1,e2,en | 15: e1,e2,ep,en
"""

scalar = basis(0)
e1     = basis(1)
e2     = basis(2)
ep     = basis(4)
en     = basis(8)
pseudo = basis(15)
eo   = 0.5 * (en - ep)
einf = en + ep

# ============

def blade_gp(a, b):
    """
    Product of two orthogonal basis blades.

    Returns:
        coefficient, output_mask
    """
    sign = 1.0

    # Sign generated by reordering basis vectors
    for i in range(DIM): # ps: dim = 4
        if (a >> i) & 1: 
            # a >> i : put the i-th bit at position 0
            # then select just the position 0 bit of a (with & 1)
            # (AKA  "does blade a contain basis vector i?")

            # count the number of bits set in b that are lower than i
            
            # 1 << i	        single bit at position i ->      building block for masks
            # (1 << i) - 1	    all bits below position i ->	"positions that come before i"
            # b & ((1<<i)-1)	b's bits below position i ->	"how many of b's factors sit before this a-factor"

            lower_bits_b = b & ((1 << i) - 1)
            if lower_bits_b.bit_count() % 2:
                sign *= -1.0  # swapping impose a sing change

    # Metric factors from repeated basis vectors
    common = a & b  # shared bit 
    # simplify commond basis according to the metric
    for i in range(DIM):
        if (common >> i) & 1:
            sign *= METRIC[i]

    # a ^ b : surviving basis vectors of the output blade
    return sign, a ^ b

def build_gp_table():
    """
    T[i,j,k] is the coefficient of blade k in blade_i * blade_j.
    """
    T = np.zeros((NBLADES, NBLADES, NBLADES))

    for i in range(NBLADES):
        for j in range(NBLADES):
            coefficient, k = blade_gp(i, j)
            T[i, j, k] = coefficient

    return T

def build_outer_table():
    table = np.zeros((NBLADES, NBLADES, NBLADES))

    for i in range(NBLADES):
        for j in range(NBLADES):
            if i & j == 0:
                coefficient, k = blade_gp(i, j)
                table[i, j,k] = coefficient

    return table

def build_inner_table():
    table = np.zeros((NBLADES, NBLADES, NBLADES))

    for i in range(NBLADES):
        grade_i = blade_grade(i)

        for j in range(NBLADES):
            grade_j = blade_grade(j)
            coefficient, k = blade_gp(i, j)

            if blade_grade(k) == abs(grade_i - grade_j):
                table[i, j, k] = coefficient

    return table


def generate_operator(table):
    return lambda a, b: np.einsum("...i,...j,ijk->...k", a, b, table)

